export const FAQ_CONTENT = [
  {
    id: 1,
    title: "What kind of coding errors does your tool help fix?",
    answer:
      "Our tool can help fix a variety of coding errors, including syntax errors, logical errors, performance issues and even run-time errors. We use advanced algorithms and machine learning techniques to analyze your code and provide suggestions for improvement.",
  },
  {
    id: 2,
    title: "How does your tool perform code reviews?",
    answer:
      "CodeMate can analyze your code against best practices and industry standards to help identify potential issues and improve the overall quality of your code. We can provide feedback on things like code style, naming guidelines, formatting, documentation, and more.",
  },
  {
    id: 3,
    title: "Can your tool optimize code automatically?",
    answer:
      "Yes, our tool can suggest optimizations for your code, such as identifying areas where you can use more efficient algorithms or data structures. However, it's up to you to implement these optimizations in your code.",
  },
  {
    id: 4,
    title: "Can your tool be used with any programming language?",
    answer:
      "Our tool currently supports 30+ programming languages(Python, JavaScript, Java, C++, C#, PHP, TypeScript, Ruby, Swift, Go, Kotlin, Rust, R, MATLAB, Perl, Shell scripting, SQL, Objective-C, Scala, Haskell, Dart, Elixir, Erlang, Fortran and Prolog. and many more). We're constantly adding support for new languages, so if you don't see your language working with CodeMate, please contact us and let us know. Moreover, you can also train your own CodeMate version with any programming language or framework by importing its GitHub repository link.",
  },
  {
    id: 5,
    title: "Is my code kept private and secure?",
    answer:
      "Yes, we take the security and privacy of your code very seriously. We use industry-standard encryption and security protocols to protect your code and ensure that it remains private and secure at all times.",
  },
  {
    id: 6,
    title: "How do I get started with your tool?",
    answer:
      "CodeMate offers a quick and easy way to fix your coding errors, without the need for switching your existing environment. If you are working in Visual Studio Code, you can simply install CodeMate extension there and start using. Or else, you can use our own IDE to code and fix your errors.",
  },
  {
    id: 7,
    title: "How accurate is results generated by CodeMate?",
    answer:
      "The accuracy of the results generated by CodeMate depends on several factors, including the quality and specificity of the code description provided by the user. Our models are trained on the latest data available from sources such as Stack Overflow and open-source repositories, but it's important to note that they may not always produce perfect results. However, users can edit and refine the results as needed to ensure that they meet their specific requirements. Overall, we strive to provide the most accurate and useful results possible to help developers improve their code.",
  },
];
